package com.mycompany.uposts.domain.constant;

public enum Code {

    REQUEST_VALIDATION_ERROR,
    NICKNAME_BUSY,
    INTERNAL_SERVER_ERROR,
    TEST,
    USER_NOT_FOUND,
    AUTHORIZATION_ERROR,
    MISSING_REQUEST_HEADER,
    NOT_READABLE,
    SUBSCRIPTION_LOGIC_ERROR,
    PUBLISHER_NOT_FOUND,
    ALREADY_SUBSCRIBED
}
